USE [Newtouch_CIS]
GO

-- 事件类型: ALTER_TABLE
-- 变更时间: 11/19/2024 17:09:58
ALTER TABLE dbo.zy_PatDxInfo ADD CONSTRAINT
	PK_ZY_PATDXINFO PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
