USE [NewtouchHIS_Base]
GO

-- 事件类型: ALTER_PROCEDURE
-- 变更时间: 11/19/2024 17:58:32



/***
exec [RPT_ERM_病案首页信息] '6d5752a7-234a-403e-aa1c-df8b45d3469f','03245'

***/
ALTER   proc [dbo].[RPT_ERM_病案首页信息]
    @orgId varchar(50),
    @zyh varchar(15)
as
SELECT
    isnull(a.Id,'-')Id,
    isnull(b.YLFKFS,'-') '医疗付款方式',
        isnull(a.JKKH,'-')  '就诊号',
        isnull(a.ZYCS,'-') '住院次数',
        isnull(a.BAH,'-') '病案号',
        isnull(a.PATID,'-') '病人ID',
        isnull(a.ZYH,'-') '住院号',
        isnull(a.XM,'-') '姓名',
        isnull(a.XB,'-') '性别',
        isnull(convert(varchar(10),a.CSRQ,120),'-') '出生日期',
        (case when a.NL>0 then convert(varchar(10),a.NL)+'岁' else '-' end) '年龄',
        isnull(a.GJ,'-') '国籍',
        (case when a.BZYZSNL>0 then convert(varchar(10),a.BZYZSNL)+'月' else '-' end) '不足一周岁年龄',
        isnull(convert(varchar(10),a.XSECSTZ),'-') '新生儿出生体重',
        isnull(convert(varchar(10),a.XSERYTZ),'-') '新生儿入院体重',
        ( case when isnull(a.CSD_SN,'')+isnull(a.CSD_SI,'')+isnull(a.CSD_QX,'')+isnull(a.CSD_JD,'')+isnull(a.CSD,'')>'' then isnull(a.CSD_SN,'')+isnull(a.CSD_SI,'')+isnull(a.CSD_QX,'')+isnull(a.CSD_JD,'')+isnull(a.CSD,'') else '-' end) '出生地',
        isnull(a.GG,'-') '籍贯',
        isnull(a.MZ,'-') '民族',
        isnull(a.SFZH,'-') '身份证号',
        isnull(a.ZY,'-') '职业',
    left(isnull(b.HY,'-'),1) '婚姻',
    ( case when isnull(a.XZZ_SN,'')+isnull(a.XZZ_SI,'')+isnull(a.XZZ_QX,'')+isnull(a.XZZ_JD,'')+isnull(a.XZZ,'')>'' then isnull(a.XZZ_SN,'')+isnull(a.XZZ_SI,'')+isnull(a.XZZ_QX,'')+isnull(a.XZZ_JD,'')+isnull(a.XZZ,'') else '-' end) '现住址',
    isnull(a.DH,'-') '电话',
    isnull(a.XZZYB,'-') '现住址邮编',
    ( case when isnull(a.HKDZ_SN,'')+isnull(a.HKDZ_SI,'')+isnull(a.HKDZ_QX,'')+isnull(a.HKDZ_JD,'')+isnull(a.HKDZ,'')>'' then  isnull(a.HKDZ_SN,'')+isnull(a.HKDZ_SI,'')+isnull(a.HKDZ_QX,'')+isnull(a.HKDZ_JD,'')+isnull(a.HKDZ,'') else '-' end ) '户口地址',
    isnull(a.HKDYB,'-') '户口地邮编',
    isnull(a.GZDWJDZ,'-') '工作单位及地址',
    isnull(a.DWDH,'-') '单位电话',
    isnull(a.DWYB,'-') '单位邮编',
    isnull(a.LXRXM,'-') '联系人姓名',
    isnull(a.GX,'-') '关系',
    ( case when isnull(a.LXRDZ_SN,'')+isnull(a.LXRDZ_SI,'')+isnull(a.LXRDZ_QX,'')+isnull(a.LXRDZ_JD,'')+isnull(a.LXRDZ,'')>'' then isnull(a.LXRDZ_SN,'')+isnull(a.LXRDZ_SI,'')+isnull(a.LXRDZ_QX,'')+isnull(a.LXRDZ_JD,'')+isnull(a.LXRDZ,'') else '' end) '联系人地址',
    isnull(a.LXRDH,'-') '联系人电话',
    (case a.RYTJ when 1 then 2 when 2 then 1 when 3 then 3 else 9 end) '入院途径',
    isnull(convert(varchar(20),a.RYSJ,120),'-') '入院时间',
    isnull(convert(varchar(10),a.RYSJS),'-') '入院时间小时',
    isnull(a.RYKB,'-') '入院科别',
    isnull(a.RYBF,'-') '入院病房',
    isnull(a.ZKKB,'-') '转院科别',
    isnull(convert(varchar(20),a.CYSJ,120),'-') '出院时间',
    isnull(convert(varchar(10),a.CYSJS),'-') '出院时间小时',
    isnull(a.CYKB,'-') '出院科别',
    isnull(a.CYBF,'-') '出院病房',
    isnull(a.SJZYTS,'-') '实际住院天数',
    isnull(a.MZZD,'-') '门诊诊断',
    isnull(a.MZZDDM,'-') '门诊诊断代码',
	isnull(a.RYZD,'-') '住院诊断',
    isnull(a.RYZDDM,'-') '住院诊断代码',
	isnull(a.SSLCLJ,'-') '实施临床路径',
	isnull(a.ZYSSLCLJ,'-') '住院实施临床路径',
	isnull(a.SYYLJGZYZJ,'-') '使用医疗机构中药制剂',
	isnull(a.SYZYZLSB,'-') '使用中医诊疗设备	',
	isnull(a.SYZYZLJS,'-') '使用中医诊疗技术',
	isnull(a.BZSH,'-') '辩证施护',
    case a.SSLCLJ when '1' then '是' when '2' then '否' else '-'end as SSLCLJ,
    case a.WCLCLJ when '1' then '是' when '2' then '否' else '-'end as WCLCLJ,
    isnull(a.TCYY,'') as '退出原因',
    case a.SFBY when '1' then '是' when '2' then '否' else '-'end as '是否变异',
    case a.BYYY when '1' then '正变异' when '2' then '负变异' when '3' then '系统原因' else '-' end as '变异原因',
    isnull(convert(varchar(10),a.QJCS),'-')QJCS,
    isnull(convert(varchar(10),a.QJCGCS),'-')QJCGCS,
    isnull(convert(varchar(10),a.QZRQ,120),'-')QZRQ,
    isnull(a.ZQSS,'-')ZQSS,
    isnull(a.BRLY,'-')BRLY,
    isnull(a.WBYY,'-') '损伤、中毒的外部原因',
    isnull(a.H23,'-') '疾病编码',
    isnull(a.BLZD,'-') '病理诊断',
    isnull(a.BLZDDM,'-') '病理疾病编码',
    isnull(a.BLH,'-') '病理号',
    isnull(a.YWGM,'-') '药物过敏',
    isnull(a.GMYW,'-') '过敏药物',
    (case a.SWHZSJ when  '1' then '2' when '2' then '1' else '-' end) '死亡患者尸检',
    isnull(a.XX,'-') '血型',
    isnull(a.RH,'-') RH,
    isnull(a.KZR,'-') '科主任',
    isnull(a.ZRYS,'-') '主任（副主任）医师',
    isnull(a.ZZYS,'-') '主诊医师',
    isnull(a.ZZYS1,'-') '主治医师',
    isnull(a.ZYYS,'-') '住院医师',
    isnull(a.ZRHS,'-')'责任护士',
    isnull(a.JXYS,'-') '进修医师',
    isnull(a.SXYS,'-') '实习医师',
    isnull(a.BMY,'-') '编码员',
    isnull(a.BAZL,'-') '病案质量',
    isnull(a.ZKYS,'-') '质控医师',
    isnull(a.ZKHS,'-') '质控护士',
    isnull(convert(varchar(10),a.ZKRQ),'-') '质控日期',
    case a.LYFS when '1' then '医嘱离院' when '2' then '医嘱转院' when '3' then '医嘱转社区卫生服务机构/乡镇卫生院' when '4' then '非医嘱离院' when '5' then '死亡' when '9' then '其他' else '-' end as '离院方式',
    isnull(a.YZZY_YLJG,'-') '医嘱转院医疗机构',
    isnull(a.WSY_YLJG,'-') '卫生院医疗机构',
    (case a.SFZZYJH when 1 then '无' when 2 then '有' else '-' end) '是否再住院计划',
    isnull(a.MD,'-') '目的',
    isnull(convert(varchar(10),a.RYQ_T),'-') '入院前_天',
    isnull(convert(varchar(10),a.RYQ_XS),'-') '入院前_小时',
    isnull(convert(varchar(10),a.RYQ_F),'-') '入院前_分',
    isnull(convert(varchar(10),a.RYH_T),'-') '入院后_天',
    isnull(convert(varchar(10),a.RYH_XS),'-') '入院后_小时',
    isnull(convert(varchar(10),a.RYH_F),'-') '入院后_分',
    isnull(a.zt,'-')zt,isnull(convert(varchar(20),a.CreateTime,120),'-')CreateTime,isnull(a.CreatorCode,'-')CreatorCode,
    isnull(convert(varchar(20),a.LastModifyTime,120),'-')LastModifyTime,isnull(a.LastModifierCode,'-')LastModifierCode,
    isnull(a.LCLJGL,'-')LCLJGL,isnull(a.LCBZGL,'-')LCBZGL,isnull(a.BZGLFL,'-')BZGLFL,isnull(b.BQFX,'-') '病情分型',isnull(a.OrganizeId,'-')OrganizeId,
    isnull(a.RYCH,'-')RYCH,isnull(a.CYCH,'-')CYCH,isnull(a.bazt,'-')bazt,isnull(a.ZFY,0.00) '住院费',isnull(a.ZFJE,0.00) '自付金额',
    isnull(a.YLFUF,0.00) '医疗服务费',isnull(a.BZLZF,0.00)BZLZF,isnull(a.ZYBLZHZF,0.00)ZYBLZHZF,isnull(a.ZLCZF,0.00) '一般治疗操作费',
    isnull(a.HLF,0.00) '护理费',isnull(a.QTFY,0) '其他费用',isnull(a.BLZDF,0.00) '病理诊断费',isnull(a.SYSZDF,0.00) '实验室诊断费',isnull(a.YXXZDF,0.00)'影像学诊断费',
    isnull(a.LCZDXMF,0.00) '临床诊断项目费',isnull(a.FSSZLXMF,0.00) '非手术治疗项目费',isnull(a.WLZLF,0.00) '临床物理治疗费',isnull(a.SSZLF,0.00) '手术治疗费',
    isnull(a.MAF,0.00) '麻醉费',isnull(a.SSF,0.00) '手术费',isnull(a.KFF,0.00) '康复费',isnull(a.ZYZLF,0.00) '中医治疗费',isnull(a.ZYZL,0.00)ZYZL,
    isnull(a.ZYWZ,0.00)ZYWZ,isnull(a.ZYGS,0.00)ZYGS,isnull(a.ZCYJF,0.00)ZCYJF,isnull(a.ZYTNZL,0.00)ZYTNZL,isnull(a.ZYGCZL,0.00)ZYGCZL,
    isnull(a.ZYTSZL,0.00)ZYTSZL,isnull(a.ZYQT,0.00)ZYQT,isnull(a.ZYTSTPJG,0.00)ZYTSTPJG,isnull(a.BZSS,0.00)BZSS,isnull(a.XYF,0.00) '西药费',
    isnull(a.KJYWF,0.00) '抗菌药物费用',isnull(a.ZCYF,0.00) '中成药费',isnull(a.ZYZJF,0.00)ZYZJF,isnull(a.ZCYF1,0.00) '中草药费',isnull(a.XF,0.00) '血费',
    isnull(a.BDBLZPF,0.00) '白蛋白类制品费',isnull(a.QDBLZPF,0.00) '球蛋白类制品费',isnull(a.NXYZLZPF,0.00) '凝血因子类制品费',isnull(a.XBYZLZPF,0.00) '细胞因子类制品费',
    isnull(a.HCYYCLF,0.00) '检查用一次性医用材料费',isnull(a.YYCLF,0.00) '治疗用一次性医用材料费',isnull(a.YCXYYCLF,0.00) '手术用一次性医用材料费',
    isnull(a.QTF,0.00) '其他费',
    a.HXB as '红细胞',
    a.XXB as '血小板',
    a.XJ as '血浆',
    a.QX as '全血',
    a.ZTXHS as '自体血回输',
    a.BDB  as '白蛋白',
    a.LCD as '冷沉淀',
    a.QT as '其他',
    a.SXFY as '输血反应',
    case a.SZ when 1 then '是' when 2 then '否' else '-' end as '随诊',
    a.SZQXZ as '随诊期限周',
    a.SZQXY as '随诊期限月',
    a.SZQXN  as '随诊期限年',
    a.SYCXSJ as 'SYCXSJ',
    isnull(a.lhyy,'-') as '联合用药',
    case a.CT when '1' then '阳性' when '2' then '阴性' when '3' then '未做' end  as 'CT',
    case a.PETCT when '1' then '阳性' when '2' then '阴性' when '3' then '未做' end  as 'PETCT',
    case a.SYCT when '1' then '阳性' when '2' then '阴性' when '3' then '未做' end  as '双源CT',
    case a.BC when '1' then '阳性' when '2' then '阴性' when '3' then '未做' end  as 'B超',
    case a.XP when '1' then '阳性' when '2' then '阴性' when '3' then '未做' end  as 'X片',
    case a.CSXDT when '1' then '阳性' when '2' then '阴性' when '3' then '未做' end  as '超声心动图',
    case a.MRI when '1' then '阳性' when '2' then '阴性' when '3' then '未做' end  as 'MRI',
    case a.TWSJC when '1' then '阳性' when '2' then '阴性' when '3' then '未做' end  as '同位素检查',
    case a.YYGRQK when '1' then '无' when '2' then '有' else '-' end as '医院感染情况',
    case a.YYGRSSXG when '1' then '否' when '2' then '是' else '-' end as '医院感染是否与手术相关',
    case a.YYGRSFQRXG when '1' then '无' when '2' then '有' else '-' end as '医院感染是否与侵入性操作性相关',
    case a.KJYWSYQK when '1' then 'Ⅰ联' when '2' then 'Ⅱ联' when '3' then 'Ⅲ联' when '4' then 'Ⅳ联' when '5' then '>Ⅵ联' else '-' end as '抗菌药物使用情况',
    a.KJYWMC1 as '抗菌药物名称1',a.KJYWMC2 as '抗菌药物名称2', a.KJYWMC3 as '抗菌药物名称3' , a.KJYWMC4 as '抗菌药物名称4', a.KJYWMC5 as '抗菌药物名称5',a.KJYWMC6 as '抗菌药物名称6',
    case a.SFFSYC  when '1' then '否' when '2' then '是' else '-' end as '是否发生压疮',
    case a.SFZYQJFS  when '1' then '否' when '2' then '是' else '-' end as '是否住院期间发生',
    case a.YCFQ  when '1' then '1期' when '2' then '2期' when '3' then '3期' when '4' then '4期' else '-' end as '压疮分期',
    case a.SYFY  when '0' then '未输' when '1' then '无' when '2' then '有' else '-' end as '输液反应',
    a.YFFYDYW as '引发反应的药物',
    a.SYLCBX as '临床表现',
    case a.ZYSFDDHZC  when '1' then '否' when '2' then '是' else '-' end as '住院期间是否发生跌倒或坠床',
    case a.ZYDDHZCDCD when '1' then '一级' when '2' then '二级' when '3' then '三级' when '4' then '未造成伤害' else '-' end as '住院期间跌倒或坠床的伤害程度',
    case a.DDHZCDYY when '1' then '健康原因' when '2' then '治疗，药物，麻醉原因' when '3' then '环境因素' when '4' then '其他原因' else '-' end as '跌倒或坠床的原因',
    case a.ZYQJSTYY when '1' then '无' when '2' then '有' else '-' end as '住院期间身体约束',
    a.LYTXNSDZ as '离院时透析尿素氮值'
FROM  Newtouch_EMR..mr_basy a with(nolock),Newtouch_EMR..mr_basy_rel_code b with(nolock)
where a.organizeid=b.organizeid and a.zt='1' and a.id=b.SYId
  and a.ZYH=@zyh and a.organizeid=@orgId

