//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newtouch.Herp.DomainServices.PurchaseWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.framework.shys.wondersgroup.com/", ConfigurationName="PurchaseWebService.DispatcherService")]
    public interface DispatcherService {
        
        // CODEGEN: 命名空间  的元素名称 sUser 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvResponse SendRecv(Newtouch.Herp.DomainServices.PurchaseWebService.SendRecv request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvResponse> SendRecvAsync(Newtouch.Herp.DomainServices.PurchaseWebService.SendRecv request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRecv {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRecv", Namespace="http://ws.framework.shys.wondersgroup.com/", Order=0)]
        public Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvBody Body;
        
        public SendRecv() {
        }
        
        public SendRecv(Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendRecvBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sJgbm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sVersion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sXxlx;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sSign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string xmlData;
        
        public SendRecvBody() {
        }
        
        public SendRecvBody(string sUser, string sPwd, string sJgbm, string sVersion, string sXxlx, string sSign, string xmlData) {
            this.sUser = sUser;
            this.sPwd = sPwd;
            this.sJgbm = sJgbm;
            this.sVersion = sVersion;
            this.sXxlx = sXxlx;
            this.sSign = sSign;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRecvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRecvResponse", Namespace="http://ws.framework.shys.wondersgroup.com/", Order=0)]
        public Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvResponseBody Body;
        
        public SendRecvResponse() {
        }
        
        public SendRecvResponse(Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendRecvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SendRecvResponseBody() {
        }
        
        public SendRecvResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DispatcherServiceChannel : Newtouch.Herp.DomainServices.PurchaseWebService.DispatcherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DispatcherServiceClient : System.ServiceModel.ClientBase<Newtouch.Herp.DomainServices.PurchaseWebService.DispatcherService>, Newtouch.Herp.DomainServices.PurchaseWebService.DispatcherService {
        
        public DispatcherServiceClient() {
        }
        
        public DispatcherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DispatcherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DispatcherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DispatcherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvResponse Newtouch.Herp.DomainServices.PurchaseWebService.DispatcherService.SendRecv(Newtouch.Herp.DomainServices.PurchaseWebService.SendRecv request) {
            return base.Channel.SendRecv(request);
        }
        
        public string SendRecv(string sUser, string sPwd, string sJgbm, string sVersion, string sXxlx, string sSign, string xmlData) {
            Newtouch.Herp.DomainServices.PurchaseWebService.SendRecv inValue = new Newtouch.Herp.DomainServices.PurchaseWebService.SendRecv();
            inValue.Body = new Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvBody();
            inValue.Body.sUser = sUser;
            inValue.Body.sPwd = sPwd;
            inValue.Body.sJgbm = sJgbm;
            inValue.Body.sVersion = sVersion;
            inValue.Body.sXxlx = sXxlx;
            inValue.Body.sSign = sSign;
            inValue.Body.xmlData = xmlData;
            Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvResponse retVal = ((Newtouch.Herp.DomainServices.PurchaseWebService.DispatcherService)(this)).SendRecv(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvResponse> Newtouch.Herp.DomainServices.PurchaseWebService.DispatcherService.SendRecvAsync(Newtouch.Herp.DomainServices.PurchaseWebService.SendRecv request) {
            return base.Channel.SendRecvAsync(request);
        }
        
        public System.Threading.Tasks.Task<Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvResponse> SendRecvAsync(string sUser, string sPwd, string sJgbm, string sVersion, string sXxlx, string sSign, string xmlData) {
            Newtouch.Herp.DomainServices.PurchaseWebService.SendRecv inValue = new Newtouch.Herp.DomainServices.PurchaseWebService.SendRecv();
            inValue.Body = new Newtouch.Herp.DomainServices.PurchaseWebService.SendRecvBody();
            inValue.Body.sUser = sUser;
            inValue.Body.sPwd = sPwd;
            inValue.Body.sJgbm = sJgbm;
            inValue.Body.sVersion = sVersion;
            inValue.Body.sXxlx = sXxlx;
            inValue.Body.sSign = sSign;
            inValue.Body.xmlData = xmlData;
            return ((Newtouch.Herp.DomainServices.PurchaseWebService.DispatcherService)(this)).SendRecvAsync(inValue);
        }
    }
}
