//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newtouch.HIS.Proxy.GuiAnXnhReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.hisinterface.hzyl.aspirecn.com/", ConfigurationName="GuiAnXnhReference.HisService")]
    public interface HisService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Newtouch.HIS.Proxy.GuiAnXnhReference.request1Response request1(Newtouch.HIS.Proxy.GuiAnXnhReference.request1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Newtouch.HIS.Proxy.GuiAnXnhReference.request1Response> request1Async(Newtouch.HIS.Proxy.GuiAnXnhReference.request1 request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Newtouch.HIS.Proxy.GuiAnXnhReference.requestResponse request(Newtouch.HIS.Proxy.GuiAnXnhReference.request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Newtouch.HIS.Proxy.GuiAnXnhReference.requestResponse> requestAsync(Newtouch.HIS.Proxy.GuiAnXnhReference.request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class request1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="request1", Namespace="http://webservice.hisinterface.hzyl.aspirecn.com/", Order=0)]
        public Newtouch.HIS.Proxy.GuiAnXnhReference.request1Body Body;
        
        public request1() {
        }
        
        public request1(Newtouch.HIS.Proxy.GuiAnXnhReference.request1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class request1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public request1Body() {
        }
        
        public request1Body(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class request1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="request1Response", Namespace="http://webservice.hisinterface.hzyl.aspirecn.com/", Order=0)]
        public Newtouch.HIS.Proxy.GuiAnXnhReference.request1ResponseBody Body;
        
        public request1Response() {
        }
        
        public request1Response(Newtouch.HIS.Proxy.GuiAnXnhReference.request1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class request1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public request1ResponseBody() {
        }
        
        public request1ResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="request", Namespace="http://webservice.hisinterface.hzyl.aspirecn.com/", Order=0)]
        public Newtouch.HIS.Proxy.GuiAnXnhReference.requestBody Body;
        
        public request() {
        }
        
        public request(Newtouch.HIS.Proxy.GuiAnXnhReference.requestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class requestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public requestBody() {
        }
        
        public requestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="requestResponse", Namespace="http://webservice.hisinterface.hzyl.aspirecn.com/", Order=0)]
        public Newtouch.HIS.Proxy.GuiAnXnhReference.requestResponseBody Body;
        
        public requestResponse() {
        }
        
        public requestResponse(Newtouch.HIS.Proxy.GuiAnXnhReference.requestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class requestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public requestResponseBody() {
        }
        
        public requestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HisServiceChannel : Newtouch.HIS.Proxy.GuiAnXnhReference.HisService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HisServiceClient : System.ServiceModel.ClientBase<Newtouch.HIS.Proxy.GuiAnXnhReference.HisService>, Newtouch.HIS.Proxy.GuiAnXnhReference.HisService {
        
        public HisServiceClient() {
        }
        
        public HisServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HisServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HisServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Newtouch.HIS.Proxy.GuiAnXnhReference.request1Response Newtouch.HIS.Proxy.GuiAnXnhReference.HisService.request1(Newtouch.HIS.Proxy.GuiAnXnhReference.request1 request) {
            return base.Channel.request1(request);
        }
        
        public string request1(string arg0, string arg1, string arg2) {
            Newtouch.HIS.Proxy.GuiAnXnhReference.request1 inValue = new Newtouch.HIS.Proxy.GuiAnXnhReference.request1();
            inValue.Body = new Newtouch.HIS.Proxy.GuiAnXnhReference.request1Body();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            Newtouch.HIS.Proxy.GuiAnXnhReference.request1Response retVal = ((Newtouch.HIS.Proxy.GuiAnXnhReference.HisService)(this)).request1(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Newtouch.HIS.Proxy.GuiAnXnhReference.request1Response> Newtouch.HIS.Proxy.GuiAnXnhReference.HisService.request1Async(Newtouch.HIS.Proxy.GuiAnXnhReference.request1 request) {
            return base.Channel.request1Async(request);
        }
        
        public System.Threading.Tasks.Task<Newtouch.HIS.Proxy.GuiAnXnhReference.request1Response> request1Async(string arg0, string arg1, string arg2) {
            Newtouch.HIS.Proxy.GuiAnXnhReference.request1 inValue = new Newtouch.HIS.Proxy.GuiAnXnhReference.request1();
            inValue.Body = new Newtouch.HIS.Proxy.GuiAnXnhReference.request1Body();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((Newtouch.HIS.Proxy.GuiAnXnhReference.HisService)(this)).request1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Newtouch.HIS.Proxy.GuiAnXnhReference.requestResponse Newtouch.HIS.Proxy.GuiAnXnhReference.HisService.request(Newtouch.HIS.Proxy.GuiAnXnhReference.request request) {
            return base.Channel.request(request);
        }
        
        public string request(string arg0, string arg1) {
            Newtouch.HIS.Proxy.GuiAnXnhReference.request inValue = new Newtouch.HIS.Proxy.GuiAnXnhReference.request();
            inValue.Body = new Newtouch.HIS.Proxy.GuiAnXnhReference.requestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Newtouch.HIS.Proxy.GuiAnXnhReference.requestResponse retVal = ((Newtouch.HIS.Proxy.GuiAnXnhReference.HisService)(this)).request(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Newtouch.HIS.Proxy.GuiAnXnhReference.requestResponse> Newtouch.HIS.Proxy.GuiAnXnhReference.HisService.requestAsync(Newtouch.HIS.Proxy.GuiAnXnhReference.request request) {
            return base.Channel.requestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Newtouch.HIS.Proxy.GuiAnXnhReference.requestResponse> requestAsync(string arg0, string arg1) {
            Newtouch.HIS.Proxy.GuiAnXnhReference.request inValue = new Newtouch.HIS.Proxy.GuiAnXnhReference.request();
            inValue.Body = new Newtouch.HIS.Proxy.GuiAnXnhReference.requestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((Newtouch.HIS.Proxy.GuiAnXnhReference.HisService)(this)).requestAsync(inValue);
        }
    }
}
