//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newtouch.HIS.DomainServices.PurchaseWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://main.service.local.wondersgroup.com/", ConfigurationName="PurchaseWebService.YsxtMainService")]
    public interface YsxtMainService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvResponse sendRecv(Newtouch.HIS.DomainServices.PurchaseWebService.sendRecv request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvResponse> sendRecvAsync(Newtouch.HIS.DomainServices.PurchaseWebService.sendRecv request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRecv {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRecv", Namespace="http://main.service.local.wondersgroup.com/", Order=0)]
        public Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvBody Body;
        
        public sendRecv() {
        }
        
        public sendRecv(Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendRecvBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string arg6;
        
        public sendRecvBody() {
        }
        
        public sendRecvBody(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRecvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRecvResponse", Namespace="http://main.service.local.wondersgroup.com/", Order=0)]
        public Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvResponseBody Body;
        
        public sendRecvResponse() {
        }
        
        public sendRecvResponse(Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendRecvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sendRecvResponseBody() {
        }
        
        public sendRecvResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface YsxtMainServiceChannel : Newtouch.HIS.DomainServices.PurchaseWebService.YsxtMainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YsxtMainServiceClient : System.ServiceModel.ClientBase<Newtouch.HIS.DomainServices.PurchaseWebService.YsxtMainService>, Newtouch.HIS.DomainServices.PurchaseWebService.YsxtMainService {
        
        public YsxtMainServiceClient() {
        }
        
        public YsxtMainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YsxtMainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YsxtMainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YsxtMainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvResponse Newtouch.HIS.DomainServices.PurchaseWebService.YsxtMainService.sendRecv(Newtouch.HIS.DomainServices.PurchaseWebService.sendRecv request) {
            return base.Channel.sendRecv(request);
        }
        
        public string sendRecv(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6) {
            Newtouch.HIS.DomainServices.PurchaseWebService.sendRecv inValue = new Newtouch.HIS.DomainServices.PurchaseWebService.sendRecv();
            inValue.Body = new Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvResponse retVal = ((Newtouch.HIS.DomainServices.PurchaseWebService.YsxtMainService)(this)).sendRecv(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvResponse> Newtouch.HIS.DomainServices.PurchaseWebService.YsxtMainService.sendRecvAsync(Newtouch.HIS.DomainServices.PurchaseWebService.sendRecv request) {
            return base.Channel.sendRecvAsync(request);
        }
        
        public System.Threading.Tasks.Task<Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvResponse> sendRecvAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6) {
            Newtouch.HIS.DomainServices.PurchaseWebService.sendRecv inValue = new Newtouch.HIS.DomainServices.PurchaseWebService.sendRecv();
            inValue.Body = new Newtouch.HIS.DomainServices.PurchaseWebService.sendRecvBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            return ((Newtouch.HIS.DomainServices.PurchaseWebService.YsxtMainService)(this)).sendRecvAsync(inValue);
        }
    }
}
